{
 "title": "HCL Workload Automation Grafana Dashboard for Distributed environments 9.5 FP4",
 "description": "Visualize Workload Automation metrics",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Namespace",
    "query": "label_values(container_cpu_usage_seconds_total{pod=~\".*-(waserver|waconsole|waagent)-.*\"}, namespace)"
   },
   {
    "name": "Release",
    "query": "label_values(container_cpu_usage_seconds_total{pod=~\".*-(waserver|waconsole|waagent)-.*\", namespace=~\"[[Namespace]]\"}, pod)"
   },
   {
    "name": "POD",
    "query": "label_values(container_cpu_usage_seconds_total{pod=~\"[[Release]]-(waserver|waconsole|waagent)-.*\", namespace=~\"[[Namespace]]\"}, pod)"
   },
   {
    "name": "dur",
    "label": "moving average",
    "query": "[1m],[5m],[10m],[30m],[1h],[1d],[7d]"
   },
   { "name": "cpuDur", "query": "[45s]" },
   {
    "name": "Crticaljobname",
    "label": "Critical Job Name",
    "query": "label_values(application_wa_criticalJob_confidence_factor, jobName)\n\n\n"
   },
   {
    "name": "WorstationStatus",
    "label": "Worstation ",
    "query": "label_values(application_wa_workstation_linked_boolean, workstation)"
   },
   {
    "name": "JobsByFolder",
    "label": "Folder",
    "query": "label_values(application_wa_JobsByFolder_jobs, folder)"
   }
  ]
 },
 "panels": [
  {
   "title": "Flexera Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uncounted Jobs",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "application_wa_licence_uncountedJobs_jobs{job=\"kubernetes-pods\", kubernetes_namespace=~\"[[Namespace]]\", release=~\"[[Release]]\", kubernetes_pod_name=~\"[[POD]]\"}",
       "legendFormat": "{{app_kubernetes_io_name}}"
      }
     ]
    },
    {
     "title": "Flexera Uncounted Jobs",
     "type": "graph",
     "gridPos": { "h": 8, "w": 20, "x": 4, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "application_wa_licence_uncountedJobs_jobs{job=\"kubernetes-pods\", kubernetes_namespace=~\"[[Namespace]]\", release=~\"[[Release]]\", kubernetes_pod_name=~\"[[POD]]\"}",
       "legendFormat": "{{app_kubernetes_io_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Workload",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Workload by Job Status",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(clamp_min(application_wa_JobsInPlanCount_job{kubernetes_namespace=~\"[[Namespace]]\", release=~\"[[Release]]\",waservertype=\"master\"},0)) by (jobstatus)",
       "legendFormat": "{{jobstatus}}"
      }
     ]
    },
    {
     "title": "Job Status by Workstation",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(clamp_min(application_wa_JobsByWorkstation_jobs{kubernetes_namespace=~\"[[Namespace]]\", release=~\"[[Release]]\",waservertype=\"master\",workstation=~\"^[[WorstationStatus]]\"} ,0)) by (jobstatus)",
       "legendFormat": " {{jobstatus}}"
      }
     ]
    },
    {
     "title": "Jobs Status  By Folder",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(clamp_min(application_wa_JobsByFolder_jobs{kubernetes_namespace=~\"[[Namespace]]\", release=~\"[[Release]]\",waservertype=\"master\",folder=~\"^[[JobsByFolder]]\"} ,0)) by (jobstatus)",
       "legendFormat": " {{jobstatus}}"
      }
     ]
    },
    {
     "title": "Workload throughput (jobs/min)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (rate(application_wa_JobsInPlanCount_job{kubernetes_namespace=~\"[[Namespace]]\", release=~\"[[Release]]\", waservertype=\"master\", jobstatus=~\"SUCCESSFUL|ERROR\"}[[dur]])*60) by (kubernetes_namespace, release)",
       "legendFormat": "{{kubernetes_namespace}} - {{release}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Critical Jobs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Incomplete Predecessor Critical Job",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "application_wa_criticalJob_incompletePredecessor_jobs{job=\"kubernetes-pods\", kubernetes_namespace=~\"[[Namespace]]\", release=~\"[[Release]]\",waservertype=\"master\",jobName=~\"^[[Crticaljobname]]\"}",
       "legendFormat": "{{jobStreamName}}.{{jobName}}"
      }
     ]
    },
    {
     "title": "Critical Job Potential Risk",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "application_wa_criticalJob_potentialRisk_boolean{kubernetes_namespace=~\"[[Namespace]]\", release=~\"[[Release]]\",waservertype=\"master\",jobName=~\"^[[Crticaljobname]]\"}",
       "legendFormat": " {{jobStreamName}}.{{jobName}}"
      }
     ]
    },
    {
     "title": "Critical Job High Risk",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "application_wa_criticalJob_highRisk_boolean{kubernetes_namespace=~\"[[Namespace]]\", release=~\"[[Release]]\",waservertype=\"master\",jobName=~\"^[[Crticaljobname]]\"}",
       "legendFormat": "{{jobStreamName}}.{{jobName}}"
      }
     ]
    },
    {
     "title": " Critical Job Confidence Factor",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "application_wa_criticalJob_confidence_factor{kubernetes_namespace=~\"[[Namespace]]\", release=~\"[[Release]]\",waservertype=\"master\",jobName=~\"^[[Crticaljobname]]\"}",
       "legendFormat": "{{jobStreamName}}.{{jobName}}"
      }
     ]
    },
    {
     "title": "Critical Job Estimate End",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "application_wa_criticalJob_estimateEnd_seconds{kubernetes_namespace=~\"[[Namespace]]\", release=~\"[[Release]]\",waservertype=\"master\",jobName=~\"^[[Crticaljobname]]\"}",
       "legendFormat": "{{jobStreamName}}.{{jobName}}"
      }
     ]
    }
   ]
  },
  {
   "title": "WA Server - Internal Message Queues",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Message Queue Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 68 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(application_wa_msgFileFill_percent{job=\"kubernetes-pods\", kubernetes_namespace=~\"[[Namespace]]\", release=~\"[[Release]]\", kubernetes_pod_name=~\"[[POD]]\"} , 0)",
       "legendFormat": "{{kubernetes_namespace}} - {{kubernetes_pod_name}} - {{msgfile}}"
      }
     ]
    },
    {
     "title": "Total Workstation Running",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count_values(\"workstation\" ,application_wa_workstation_running_boolean {kubernetes_namespace=~\"[[Namespace]]\", release=~\"[[Release]]\",waservertype=\"master\",workstation=~\"^[[WorstationStatus]]\"})"
      }
     ]
    },
    {
     "title": "Total Workstation Linked",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count_values (\"workstation\" ,application_wa_workstation_linked_boolean {kubernetes_namespace=~\"[[Namespace]]\", release=~\"[[Release]]\",waservertype=\"master\",workstation=~\"^[[WorstationStatus]]\"}) "
      }
     ]
    }
   ]
  },
  {
   "title": " Workstation Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Workstation Running ",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 69 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "application_wa_workstation_running_boolean{kubernetes_namespace=~\"[[Namespace]]\", release=~\"[[Release]]\",waservertype=\"master\",workstation=~\"^[[WorstationStatus]]\"}",
       "legendFormat": "{{workstation}}"
      }
     ]
    },
    {
     "title": "Workstation Link",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 76 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "application_wa_workstation_linked_boolean{kubernetes_namespace=~\"[[Namespace]]\", release=~\"[[Release]]\",waservertype=\"master\",workstation=~\"^[[WorstationStatus]]\"}",
       "legendFormat": "{{workstation}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Database Connection Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "DB Connection",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "application_wa_DB_connected_boolean{kubernetes_namespace=~\"[[Namespace]]\", release=~\"[[Release]]\",waservertype=\"master\"}",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "WA Server - Liberty",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Heap Usage Percentage",
     "type": "graph",
     "description": "The percentage of heap memory currently in use.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "base_memory_usedHeap_bytes{kubernetes_pod_name=~\".*-waserver-.*\", kubernetes_namespace=~\"[[Namespace]]\", release=~\"[[Release]]\", kubernetes_pod_name=~\"[[POD]]\"} / base_memory_maxHeap_bytes{kubernetes_pod_name=~\".*-waserver-.*\", kubernetes_namespace=~\"[[Namespace]]\", release=~\"[[Release]]\", kubernetes_pod_name=~\"[[POD]]\"}",
       "legendFormat": "{{kubernetes_namespace}} - {{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Active Sessions",
     "type": "graph",
     "description": "A session is considered active if the application server is processing a request that uses that user session.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "vendor_session_activeSessions{kubernetes_pod_name=~\".*-waserver-.*\", kubernetes_namespace=~\"[[Namespace]]\", release=~\"[[Release]]\", kubernetes_pod_name=~\"[[POD]]\"}",
       "legendFormat": "{{kubernetes_namespace}} - {{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Live  Sessions",
     "type": "graph",
     "description": "A session is considered live if the session is loaded into memory by the application server.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "vendor_session_liveSessions{kubernetes_pod_name=~\".*-waserver-.*\", kubernetes_namespace=~\"[[Namespace]]\", release=~\"[[Release]]\", kubernetes_pod_name=~\"[[POD]]\"}",
       "legendFormat": "{{kubernetes_namespace}} - {{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Active Threads",
     "type": "graph",
     "description": "The number of threads that are actively running tasks.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "vendor_threadpool_activeThreads{kubernetes_pod_name=~\".*-waserver-.*\", kubernetes_namespace=~\"[[Namespace]]\", release=~\"[[Release]]\", kubernetes_pod_name=~\"[[POD]]\"}",
       "legendFormat": "{{kubernetes_namespace}} - {{kubernetes_pod_name}} - {{pool}}"
      }
     ]
    },
    {
     "title": "Threadpool Size",
     "type": "graph",
     "description": "The size of the Default Executor thread pool in each instance.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "vendor_threadpool_size{kubernetes_pod_name=~\".*-waserver-.*\", kubernetes_namespace=~\"[[Namespace]]\", release=~\"[[Release]]\", kubernetes_pod_name=~\"[[POD]]\"}",
       "legendFormat": "{{kubernetes_namespace}} - {{kubernetes_pod_name}} - {{pool}}"
      }
     ]
    },
    {
     "title": "Time per Garbage Collection Cycle [[dur]] moving average",
     "type": "graph",
     "description": "The average time an instance took on a specific type of garbage collection, based on data over the last [[dur]].",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(base_gc_time_seconds{kubernetes_pod_name=~\".*-waserver-.*\", kubernetes_namespace=~\"[[Namespace]]\", release=~\"[[Release]]\", kubernetes_pod_name=~\"[[POD]]\"}[[dur]]) / rate(base_gc_total{kubernetes_pod_name=~\".*-waserver-.*\", kubernetes_namespace=~\"[[Namespace]]\", release=~\"[[Release]]\", kubernetes_pod_name=~\"[[POD]]\"}[[dur]])",
       "legendFormat": "{{kubernetes_namespace}} - {{kubernetes_pod_name}} - {{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "WA Server - Connection Pools",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Time Usage per Connection Over Last [[dur]]",
     "type": "graph",
     "description": "The average time any used connection was put in use, based on data over the last [[dur]].",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(vendor_connectionpool_inUseTime_total_seconds{kubernetes_pod_name=~\".*-waserver-.*\", kubernetes_namespace=~\"[[Namespace]]\", release=~\"[[Release]]\", kubernetes_pod_name=~\"[[POD]]\"}[[dur]]) / rate(vendor_connectionpool_usedConnections_total{kubernetes_pod_name=~\".*-waserver-.*\", kubernetes_namespace=~\"[[Namespace]]\", release=~\"[[Release]]\", kubernetes_pod_name=~\"[[POD]]\"}[[dur]]) > 0",
       "legendFormat": "{{kubernetes_namespace}} - {{kubernetes_pod_name}} - {{datasource}}"
      }
     ]
    },
    {
     "title": "Managed Connections",
     "type": "graph",
     "description": "The sum of managed connections in the free, shared, and unshared pools.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "vendor_connectionpool_managedConnections{kubernetes_pod_name=~\".*-waserver-.*\", kubernetes_namespace=~\"[[Namespace]]\", release=~\"[[Release]]\", kubernetes_pod_name=~\"[[POD]]\"}",
       "legendFormat": "{{kubernetes_namespace}} - {{kubernetes_pod_name}} - {{datasource}}"
      }
     ]
    },
    {
     "title": "Free Connections",
     "type": "graph",
     "description": "The number of managed connections in the free pool.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "vendor_connectionpool_freeConnections{kubernetes_pod_name=~\".*-waserver-.*\", kubernetes_namespace=~\"[[Namespace]]\", release=~\"[[Release]]\", kubernetes_pod_name=~\"[[POD]]\"}",
       "legendFormat": "{{kubernetes_namespace}} - {{kubernetes_pod_name}} - {{datasource}}"
      }
     ]
    },
    {
     "title": "Connection Handles",
     "type": "graph",
     "description": "The number of connections that are in use. This number might include multiple connections that are shared from a single managed connection.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "vendor_connectionpool_connectionHandles{kubernetes_pod_name=~\".*-waserver-.*\", kubernetes_namespace=~\"[[Namespace]]\", release=~\"[[Release]]\", kubernetes_pod_name=~\"[[POD]]\"}",
       "legendFormat": "{{kubernetes_namespace}} - {{kubernetes_pod_name}} - {{datasource}}"
      }
     ]
    },
    {
     "title": "Created & Destroyed Connections",
     "type": "graph",
     "description": "The total number of managed connections created and destroyed since the pool was created.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "vendor_connectionpool_create_total{kubernetes_pod_name=~\".*-waserver-.*\", kubernetes_namespace=~\"[[Namespace]]\", release=~\"[[Release]]\", kubernetes_pod_name=~\"[[POD]]\"}",
       "legendFormat": "{{kubernetes_namespace}} - {{kubernetes_pod_name}} - {{datasource}}"
      },
      {
       "expr": "- vendor_connectionpool_destroy_total{kubernetes_pod_name=~\".*-waserver-.*\", kubernetes_namespace=~\"[[Namespace]]\", release=~\"[[Release]]\", kubernetes_pod_name=~\"[[POD]]\"}",
       "legendFormat": "{{kubernetes_namespace}} - {{kubernetes_pod_name}} - {{datasource}}"
      }
     ]
    }
   ]
  },
  {
   "title": "WA Console - Liberty",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Heap Usage Percentage",
     "type": "graph",
     "description": "The percentage of heap memory currently in use.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "base_memory_usedHeap_bytes{kubernetes_pod_name=~\".*-waconsole-.*\", kubernetes_namespace=~\"[[Namespace]]\", release=~\"[[Release]]\", kubernetes_pod_name=~\"[[POD]]\"} / base_memory_maxHeap_bytes{kubernetes_pod_name=~\".*-waconsole-.*\", kubernetes_namespace=~\"[[Namespace]]\", release=~\"[[Release]]\", kubernetes_pod_name=~\"[[POD]]\"}",
       "legendFormat": "{{kubernetes_namespace}} - {{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Active Sessions",
     "type": "graph",
     "description": "A session is considered active if the application server is processing a request that uses that user session.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "vendor_session_activeSessions{kubernetes_pod_name=~\".*-waconsole-.*\", kubernetes_namespace=~\"[[Namespace]]\", release=~\"[[Release]]\", kubernetes_pod_name=~\"[[POD]]\"}",
       "legendFormat": "{{kubernetes_namespace}} - {{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Live  Sessions",
     "type": "graph",
     "description": "A session is considered live if the session is loaded into memory by the application server.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "vendor_session_liveSessions{kubernetes_pod_name=~\".*-waconsole-.*\", kubernetes_namespace=~\"[[Namespace]]\", release=~\"[[Release]]\", kubernetes_pod_name=~\"[[POD]]\"}",
       "legendFormat": "{{kubernetes_namespace}} - {{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Active Threads",
     "type": "graph",
     "description": "The number of threads that are actively running tasks.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "vendor_threadpool_activeThreads{kubernetes_pod_name=~\".*-waconsole-.*\", kubernetes_namespace=~\"[[Namespace]]\", release=~\"[[Release]]\", kubernetes_pod_name=~\"[[POD]]\"}",
       "legendFormat": "{{kubernetes_namespace}} - {{kubernetes_pod_name}} - {{pool}}"
      }
     ]
    },
    {
     "title": "Threadpool Size",
     "type": "graph",
     "description": "The size of the Default Executor thread pool in each instance.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "vendor_threadpool_size{kubernetes_pod_name=~\".*-waconsole-.*\", kubernetes_namespace=~\"[[Namespace]]\", release=~\"[[Release]]\", kubernetes_pod_name=~\"[[POD]]\"}",
       "legendFormat": "{{kubernetes_namespace}} - {{kubernetes_pod_name}} - {{pool}}"
      }
     ]
    },
    {
     "title": "Time per Garbage Collection Cycle [[dur]] moving average",
     "type": "graph",
     "description": "The average time an instance took on a specific type of garbage collection, based on data over the last [[dur]].",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(base_gc_time_seconds{kubernetes_pod_name=~\".*-waconsole-.*\", kubernetes_namespace=~\"[[Namespace]]\", release=~\"[[Release]]\", kubernetes_pod_name=~\"[[POD]]\"}[[dur]]) / rate(base_gc_total{kubernetes_pod_name=~\".*-waconsole-.*\", kubernetes_namespace=~\"[[Namespace]]\", release=~\"[[Release]]\", kubernetes_pod_name=~\"[[POD]]\"}[[dur]])",
       "legendFormat": "{{kubernetes_namespace}} - {{kubernetes_pod_name}} - {{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "WA Console - Connection Pools",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Time Usage per Connection Over Last [[dur]]",
     "type": "graph",
     "description": "The average time any used connection was put in use, based on data over the last [[dur]].",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(vendor_connectionpool_inUseTime_total_seconds{kubernetes_pod_name=~\".*-waconsole-.*\", kubernetes_namespace=~\"[[Namespace]]\", release=~\"[[Release]]\", kubernetes_pod_name=~\"[[POD]]\"}[[dur]]) / rate(vendor_connectionpool_usedConnections_total{kubernetes_pod_name=~\".*-waconsole-.*\", kubernetes_namespace=~\"[[Namespace]]\", release=~\"[[Release]]\", kubernetes_pod_name=~\"[[POD]]\"}[[dur]]) > 0",
       "legendFormat": "{{kubernetes_namespace}} - {{kubernetes_pod_name}} - {{datasource}}"
      }
     ]
    },
    {
     "title": "Managed Connections",
     "type": "graph",
     "description": "The sum of managed connections in the free, shared, and unshared pools.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "vendor_connectionpool_managedConnections{kubernetes_pod_name=~\".*-waconsole-.*\", kubernetes_namespace=~\"[[Namespace]]\", release=~\"[[Release]]\", kubernetes_pod_name=~\"[[POD]]\"}",
       "legendFormat": "{{kubernetes_namespace}} - {{kubernetes_pod_name}} - {{datasource}}"
      }
     ]
    },
    {
     "title": "Free Connections",
     "type": "graph",
     "description": "The number of managed connections in the free pool.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "vendor_connectionpool_freeConnections{kubernetes_pod_name=~\".*-waconsole-.*\", kubernetes_namespace=~\"[[Namespace]]\", release=~\"[[Release]]\", kubernetes_pod_name=~\"[[POD]]\"}",
       "legendFormat": "{{kubernetes_namespace}} - {{kubernetes_pod_name}} - {{datasource}}"
      }
     ]
    },
    {
     "title": "Connection Handles",
     "type": "graph",
     "description": "The number of connections that are in use. This number might include multiple connections that are shared from a single managed connection.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "vendor_connectionpool_connectionHandles{kubernetes_pod_name=~\".*-waconsole-.*\", kubernetes_namespace=~\"[[Namespace]]\", release=~\"[[Release]]\", kubernetes_pod_name=~\"[[POD]]\"}",
       "legendFormat": "{{kubernetes_namespace}} - {{kubernetes_pod_name}} - {{datasource}}"
      }
     ]
    },
    {
     "title": "Created & Destroyed Connections",
     "type": "graph",
     "description": "The total number of managed connections created and destroyed since the pool was created.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "vendor_connectionpool_create_total{kubernetes_pod_name=~\".*-waconsole-.*\", kubernetes_namespace=~\"[[Namespace]]\", release=~\"[[Release]]\", kubernetes_pod_name=~\"[[POD]]\"}",
       "legendFormat": "{{kubernetes_namespace}} - {{kubernetes_pod_name}} - {{datasource}}"
      },
      {
       "expr": "- vendor_connectionpool_destroy_total{kubernetes_pod_name=~\".*-waconsole-.*\", kubernetes_namespace=~\"[[Namespace]]\", release=~\"[[Release]]\", kubernetes_pod_name=~\"[[POD]]\"}",
       "legendFormat": "{{kubernetes_namespace}} - {{kubernetes_pod_name}} - {{datasource}}"
      }
     ]
    }
   ]
  }
 ]
}